---
title: "lab1"
output: html_document
date: "2022-09-13"
author: 'hao'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```
  library(usethis, gitcreds)

  #if that doesn't work, install the packages and try the previous    line again.
  #install.packages("usethis")  #These should only be needed once
  #install.packages("gitcreds") 
  
```

```
  usethis::use_git_config(
  scope = "user",
  user.name = "Currrrrrrry",
  user.email = "11812923@mail.sustech.edu.cn")
```

```
library(tidyverse)
library(datasauRus)
```

```{r}
library(tidyverse)
library(datasauRus)
library(knitr)
#knitr::opts_chunk(fig.width=3, fig.height=3)
```

**question 1**
```{r}
data=datasaurus_dozen
nrow(data)
ncol(data)
variable.names(data)
```
```{r}
datasaurus_dozen %>%
  count(dataset) %>%
  print(13)
```
```{marginfigure}
There are 1846 rows and 3 columns in dataset datsaurus_dozen.
There are three variables which names are 'dataset', 'x' and 'y'.
```

**question2**
```{r}
dino_data = datasaurus_dozen %>%
  filter(dataset == "dino")
```
```{r}
library(ggplot2)
```
```{r,fig.height=3,fig.width=6}
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
dino_data %>%
  summarize(r = cor(x, y))
```
```{marginfigure}
It is a dinosaur like figure and it has no linear trend. As a result, the correlation is closed to 0.
```

**question3**
```{r,fig.height=3,fig.width=6}
star_data = datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
star_data %>%
  summarize(r = cor(x, y))
```
```{marginfigure}
It is a star plot and it is also non-linear scatter plot. As a result, the correlation between x and y is closed to 0. The answer looks the same as dinosaur.
```

**question4**
```{r,fig.height=3,fig.width=6}
circle_data = datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
circle_data %>%
  summarize(r = cor(x, y))
```
```{marginfigure}
It is a circle plot and a linear trend can not be found in this figure and the coefficient is closed to 0, wchich is the same as dinosaur plot.
```

**question5**
```{r,fig.height=3,fig.width=6}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```
```{r}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)
```